// const generateData = (n) =>{
//     const roles = ['user','admin'];
//     const users = [];

//     for (let i = 0; i < n; i++) {
//         users.push({
//             key:i+1,
//             username: `User ${i + 1}`,
//             fullName: `Full Name ${i + 1}`,
//             email: `user${i + 1}@example.com`,
//             role: roles[i % 2],
//             isApproved: Math.random() > 0.2,  
//             isLockedOut: Math.random() > 0.9, 
//         })
//     }
//     return users;
// } 
const generateData = [
    { key: 1, username: "User 1", fullName: "Full Name 1", email: "user1@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 2, username: "User 2", fullName: "Full Name 2", email: "user2@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 3, username: "User 3", fullName: "Full Name 3", email: "user3@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 4, username: "User 4", fullName: "Full Name 4", email: "user4@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 5, username: "User 5", fullName: "Full Name 5", email: "user5@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 6, username: "User 6", fullName: "Full Name 6", email: "user6@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 7, username: "User 7", fullName: "Full Name 7", email: "user7@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 8, username: "User 8", fullName: "Full Name 8", email: "user8@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 9, username: "User 9", fullName: "Full Name 9", email: "user9@example.com", role: "user", isApproved: false, isLockedOut: true },
    { key: 10, username: "User 10", fullName: "Full Name 10", email: "user10@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 11, username: "User 11", fullName: "Full Name 11", email: "user11@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 12, username: "User 12", fullName: "Full Name 12", email: "user12@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 13, username: "User 13", fullName: "Full Name 13", email: "user13@example.com", role: "user", isApproved: false, isLockedOut: false },
    { key: 14, username: "User 14", fullName: "Full Name 14", email: "user14@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 15, username: "User 15", fullName: "Full Name 15", email: "user15@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 16, username: "User 16", fullName: "Full Name 16", email: "user16@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 17, username: "User 17", fullName: "Full Name 17", email: "user17@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 18, username: "User 18", fullName: "Full Name 18", email: "user18@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 19, username: "User 19", fullName: "Full Name 19", email: "user19@example.com", role: "user", isApproved: false, isLockedOut: false },
    { key: 20, username: "User 20", fullName: "Full Name 20", email: "user20@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 21, username: "User 21", fullName: "Full Name 21", email: "user21@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 22, username: "User 22", fullName: "Full Name 22", email: "user22@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 23, username: "User 23", fullName: "Full Name 23", email: "user23@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 24, username: "User 24", fullName: "Full Name 24", email: "user24@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 25, username: "User 25", fullName: "Full Name 25", email: "user25@example.com", role: "user", isApproved: false, isLockedOut: true },
    { key: 26, username: "User 26", fullName: "Full Name 26", email: "user26@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 27, username: "User 27", fullName: "Full Name 27", email: "user27@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 28, username: "User 28", fullName: "Full Name 28", email: "user28@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 29, username: "User 29", fullName: "Full Name 29", email: "user29@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 30, username: "User 30", fullName: "Full Name 30", email: "user30@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 31, username: "User 31", fullName: "Full Name 31", email: "user31@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 32, username: "User 32", fullName: "Full Name 32", email: "user32@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 33, username: "User 33", fullName: "Full Name 33", email: "user33@example.com", role: "user", isApproved: false, isLockedOut: false },
    { key: 34, username: "User 34", fullName: "Full Name 34", email: "user34@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 35, username: "User 35", fullName: "Full Name 35", email: "user35@example.com", role: "user", isApproved: false, isLockedOut: true },
    { key: 36, username: "User 36", fullName: "Full Name 36", email: "user36@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 37, username: "User 37", fullName: "Full Name 37", email: "user37@example.com", role: "user", isApproved: false, isLockedOut: false },
    { key: 38, username: "User 38", fullName: "Full Name 38", email: "user38@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 39, username: "User 39", fullName: "Full Name 39", email: "user39@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 40, username: "User 40", fullName: "Full Name 40", email: "user40@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 41, username: "User 41", fullName: "Full Name 41", email: "user41@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 42, username: "User 42", fullName: "Full Name 42", email: "user42@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 43, username: "User 43", fullName: "Full Name 43", email: "user43@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 44, username: "User 44", fullName: "Full Name 44", email: "user44@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 45, username: "User 45", fullName: "Full Name 45", email: "user45@example.com", role: "user", isApproved: false, isLockedOut: true },
    { key: 46, username: "User 46", fullName: "Full Name 46", email: "user46@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 47, username: "User 47", fullName: "Full Name 47", email: "user47@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 48, username: "User 48", fullName: "Full Name 48", email: "user48@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 49, username: "User 49", fullName: "Full Name 49", email: "user49@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 50, username: "User 50", fullName: "Full Name 50", email: "user50@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 1, username: "User 1", fullName: "Full Name 1", email: "user1@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 2, username: "User 2", fullName: "Full Name 2", email: "user2@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 3, username: "User 3", fullName: "Full Name 3", email: "user3@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 4, username: "User 4", fullName: "Full Name 4", email: "user4@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 5, username: "User 5", fullName: "Full Name 5", email: "user5@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 6, username: "User 6", fullName: "Full Name 6", email: "user6@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 7, username: "User 7", fullName: "Full Name 7", email: "user7@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 8, username: "User 8", fullName: "Full Name 8", email: "user8@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 9, username: "User 9", fullName: "Full Name 9", email: "user9@example.com", role: "user", isApproved: false, isLockedOut: true },
    { key: 10, username: "User 10", fullName: "Full Name 10", email: "user10@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 11, username: "User 11", fullName: "Full Name 11", email: "user11@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 12, username: "User 12", fullName: "Full Name 12", email: "user12@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 13, username: "User 13", fullName: "Full Name 13", email: "user13@example.com", role: "user", isApproved: false, isLockedOut: false },
    { key: 14, username: "User 14", fullName: "Full Name 14", email: "user14@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 15, username: "User 15", fullName: "Full Name 15", email: "user15@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 16, username: "User 16", fullName: "Full Name 16", email: "user16@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 17, username: "User 17", fullName: "Full Name 17", email: "user17@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 18, username: "User 18", fullName: "Full Name 18", email: "user18@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 19, username: "User 19", fullName: "Full Name 19", email: "user19@example.com", role: "user", isApproved: false, isLockedOut: false },
    { key: 20, username: "User 20", fullName: "Full Name 20", email: "user20@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 21, username: "User 21", fullName: "Full Name 21", email: "user21@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 22, username: "User 22", fullName: "Full Name 22", email: "user22@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 23, username: "User 23", fullName: "Full Name 23", email: "user23@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 24, username: "User 24", fullName: "Full Name 24", email: "user24@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 25, username: "User 25", fullName: "Full Name 25", email: "user25@example.com", role: "user", isApproved: false, isLockedOut: true },
    { key: 26, username: "User 26", fullName: "Full Name 26", email: "user26@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 27, username: "User 27", fullName: "Full Name 27", email: "user27@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 28, username: "User 28", fullName: "Full Name 28", email: "user28@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 29, username: "User 29", fullName: "Full Name 29", email: "user29@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 30, username: "User 30", fullName: "Full Name 30", email: "user30@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 31, username: "User 31", fullName: "Full Name 31", email: "user31@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 32, username: "User 32", fullName: "Full Name 32", email: "user32@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 33, username: "User 33", fullName: "Full Name 33", email: "user33@example.com", role: "user", isApproved: false, isLockedOut: false },
    { key: 34, username: "User 34", fullName: "Full Name 34", email: "user34@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 35, username: "User 35", fullName: "Full Name 35", email: "user35@example.com", role: "user", isApproved: false, isLockedOut: true },
    { key: 36, username: "User 36", fullName: "Full Name 36", email: "user36@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 37, username: "User 37", fullName: "Full Name 37", email: "user37@example.com", role: "user", isApproved: false, isLockedOut: false },
    { key: 38, username: "User 38", fullName: "Full Name 38", email: "user38@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 39, username: "User 39", fullName: "Full Name 39", email: "user39@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 40, username: "User 40", fullName: "Full Name 40", email: "user40@example.com", role: "admin", isApproved: false, isLockedOut: true },
    { key: 41, username: "User 41", fullName: "Full Name 41", email: "user41@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 42, username: "User 42", fullName: "Full Name 42", email: "user42@example.com", role: "admin", isApproved: false, isLockedOut: false },
    { key: 43, username: "User 43", fullName: "Full Name 43", email: "user43@example.com", role: "user", isApproved: true, isLockedOut: false },
    { key: 44, username: "User 44", fullName: "Full Name 44", email: "user44@example.com", role: "admin", isApproved: true, isLockedOut: true },
    { key: 45, username: "User 45", fullName: "Full Name 45", email: "user45@example.com", role: "user", isApproved: false, isLockedOut: true },
    { key: 46, username: "User 46", fullName: "Full Name 46", email: "user46@example.com", role: "admin", isApproved: true, isLockedOut: false },
    { key: 47, username: "User 47", fullName: "Full Name 47", email: "user47@example.com", role: "user", isApproved: true, isLockedOut: true },
    { key: 48, username: "User 48", fullName: "Full Name 48", email: "user48@example.com", role: "admin", isApproved: false, isLockedOut: false },
    
];

export default generateData;